GET http://localhost:5134/games
// NB => everything in this file is a response header , and they have fields like content-type and cookies
###
GET http://localhost:5134/games/4

###
POST http://localhost:5134/games
Content-Type: application/json

 {
    "name"  : "Call of duty",
    "genre" : "Action" ,
    "price" : 19.99 ,
    "releasedate" : "2019-09-12" 
 }

###
PUT http://localhost:5134/games/3
Content-Type: application/json

{
    "name": "Horizons 2",
    "genre": "Adventure",
    "price": 109.99,
    "releasedate": "2023-12-13"
}

###
DELETE http://localhost:5134/games/3