GET http://localhost:5134/games
// NB => everything in this file is a response header , and they have fields like content-type and cookies
###
GET http://localhost:5134/games/3

###
POST http://localhost:5134/games
Content-Type: application/json

 {
    "name"  : "final fantasy 2",
    "genreId" : 2 ,
    "price" : 69.99 ,
    "releasedate" : "2010-09-12" 
 }

###
PUT http://localhost:5134/games/2
Content-Type: application/json

{
    "name": "Horizons 2 turbo",
    "genreid": 1 ,
    "price": 99.99,
    "releasedate": "2023-12-13"
}

###
DELETE http://localhost:5134/games/33